import { useEffect, useState } from "react";
import { Search, Bell, Menu } from "lucide-react";
import { API_URI } from "../../../config";

export default function Navbar() {
  const [profile, setProfile] = useState({ name: "Admin", email: "" });
  useEffect(() => { const load = () => fetch(`${API_URI}/admin/profile`, { headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } }).then((res) => res.json()).then((data) => data.success && setProfile(data.data)).catch(() => {}); load(); window.addEventListener("profile-updated", load); return () => window.removeEventListener("profile-updated", load); }, []);
  const avatar = profile.avatar || `https://ui-avatars.com/api/?background=2563eb&color=fff&name=${encodeURIComponent(profile.name || "Admin")}`;
  return <header className="sticky top-0 z-40 flex h-18 items-center justify-between border-b border-slate-200/80 bg-white/85 px-4 backdrop-blur-xl sm:px-6"><div className="flex items-center gap-4"><button className="rounded-lg p-2 hover:bg-gray-100 lg:hidden"><Menu size={22}/></button><h1 className="text-lg font-bold text-slate-800 sm:text-xl">Store overview</h1></div><div className="hidden w-80 items-center rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 md:flex"><Search size={18} className="text-slate-400"/><input type="text" placeholder="Search..." className="ml-2 w-full bg-transparent text-sm outline-none"/></div><div className="flex items-center gap-4"><button className="relative rounded-xl p-2.5 hover:bg-slate-100"><Bell size={20} className="text-slate-600"/><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-rose-500 ring-2 ring-white"/></button><div className="flex cursor-pointer items-center gap-3"><img src={avatar} alt={profile.name} className="h-9 w-9 rounded-full border-2 border-white object-cover shadow-sm"/><div className="hidden sm:block"><p className="text-sm font-semibold text-gray-800">{profile.name || "Admin"}</p><p className="text-xs text-gray-500">{profile.email || "Loading..."}</p></div></div></div></header>;
}
